development:
  adapter: postgresql
  host: 192.168.0.15
  port: 5432
  database: yapos_dev
  username: yapos
  encoding: unicode
  pool: 5

  password: 123456

test:
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: unicode
  database: geyiwu_test
  pool: 5
  username: geyiwu
  password: 123456

staging:
  adapter: postgresql
  # host: 192.168.0.201
  # port: 9999
  # database: crm-dev
  host: 192.168.0.15
  port: 5432
  database: crm
  encoding: unicode
  pool: 5
  username: admin
  password: 123456
  prepared_statements: true
  statement_limit: 1000

production:
  adapter: postgresql
  host: 127.0.0.1
  port: 5432
  encoding: unicode
  database: yapos
  pool: 5
  username: yapos
  password: Production2017
  prepared_statements: true
  statement_limit: 1000
